### ISSUE TITLE
where can i get a netcat download link thats not the discord

### ISSUE THREAD

**Issue by chunkywill** [BigLor96/Netcat-Revershell-NEW#2]
where can i get a netcat download link thats not the discord

**Comment by BigLor96** [comment]
You make sure you have the netcat x64 you can download it from this link "https://eternallybored.org/misc/netcat/netcat-win32-1.12.zip" after you download it inside the rar file there will be nc64, upload the nc64 to any file uploader online for example anonfiles, filehippo and etc make sure its a direct link.

**Comment by indian-crew** [comment]
Bro plz help me. When I'm downloading this nc.exe file in windows 10(victim's pc) it's showing a error when I run the .exe file " this version of nc.exe is not compatible with the version of OS you are using" 
How can I resolve it.
I have already tried all the methods which showing on google.

**Comment by BigLor96** [comment]
i think your “victims pc” have a 32bit operating system. If you are using the discord link method you  need to change that because its an 64bit, you can change from here (https://eternallybored.org/misc/netcat/netcat-win32-1.12.zip) and download the “netcat 1.11” make sure you have a direct download link to that file and replace the link inside the code. you can ask if your confused, goodluck!
